language: cpp
compiler:
  - gcc
  - clang
deploy:
  provider: releases
  secure: "rkC1JvR0El/H7Mdvubio0LwtvgNapMSVuQgqts33m3yJ5Nb27k28gOXVgE11VN3d1cik9p0JWiviBqg0hO5tv6q1empkGHxxE4MP7qwpYQexViQddODi4EJxGOgepi0rSGFehMVjY8vGXFdRAmVSIHduXnzrPQNrSzr4mWejO4o="
  file:
    - "jentos_exec/JentosIDE"
#    - Mac OS X file to come after multi OS is granted
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
#before_install:
#  - brew install qt5
install:
  - yes | sudo add-apt-repository ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update
  - sudo apt-get install qtcreator libqt5webkit5-dev qtlocation5-dev qtsensors5-dev libxslt-dev libsqlite3-dev libgstreamer-plugins-base0.10-dev
script:
  - qmake -project
  - qmake jentos_ide.pro
  - make
os:
  - linux
  - osx
